type images = {
    [key: string]: string
}

const CHAIRS = {
    benlines1: [
        require('./benlines1/1.jpg'),
        require('./benlines1/2.jpg'),
        require('./benlines1/3.jpg'),
        require('./benlines1/4.jpg'),
        require('./benlines1/5.jpg'),
        require('./benlines1/6.jpg'),
        require('./benlines1/7.jpg'),
        require('./benlines1/8.jpg'),
    ],
    benlines2: [
        require('./benlines2/1.jpg'),
        require('./benlines2/2.jpg'),
        require('./benlines2/3.jpg'),
        require('./benlines2/4.jpg'),
    ],
    chalfa4: [
        require('./chalfa4/1.jpg'),
        require('./chalfa4/2.jpg'),
        require('./chalfa4/3.jpg'),
        require('./chalfa4/4.jpg'),
        require('./chalfa4/5.jpg'),
        require('./chalfa4/6.jpg'),
        require('./chalfa4/7.jpg'),
        require('./chalfa4/8.jpg'),
    ],
    chbm1: [
        require('./chbm1/1.jpg'),
        require('./chbm1/2.jpg'),
        require('./chbm1/3.jpg'),
        require('./chbm1/4.jpg'),
    ],
    chbm2: [
        require('./chbm2/1.jpg'),
        require('./chbm2/2.jpg'),
        require('./chbm2/3.jpg'),
    ],
    chbm3: [
        require('./chbm3/1.jpg'),
        require('./chbm3/2.jpg'),
        require('./chbm3/3.jpg'),
    ],
    chbm4: [
        require('./chbm4/1.jpg'),
        require('./chbm4/2.jpg'),
        require('./chbm4/3.jpg'),
        require('./chbm4/4.jpg'),
        require('./chbm4/5.jpg'),
        require('./chbm4/6.jpg'),
    ],
    chbm5: [
        require('./chbm5/1.jpg'),
        require('./chbm5/2.jpg'),
        require('./chbm5/3.jpg'),
        require('./chbm5/4.jpg'),
        require('./chbm5/5.jpg'),
        require('./chbm5/6.jpg'),
        require('./chbm5/7.jpg'),
    ],
    chbm6: [
        require('./chbm6/1.jpg'),
        require('./chbm6/2.jpg'),
        require('./chbm6/3.jpg'),
        require('./chbm6/4.jpg'),
        require('./chbm6/5.jpg'),
        require('./chbm6/6.jpg'),
        require('./chbm6/7.jpg'),
        require('./chbm6/8.jpg'),
    ],
    chbm7: [
        require('./chbm7/1.jpg'),
        require('./chbm7/2.jpg'),
        require('./chbm7/3.jpg'),
    ],
    chbm8: [
        require('./chbm8/1.jpg'),
        require('./chbm8/2.jpg'),
        require('./chbm8/3.jpg'),
    ],
    chbm9: [
        require('./chbm9/1.jpg'),
        require('./chbm9/2.jpg'),
        require('./chbm9/3.jpg'),
        require('./chbm9/4.jpg'),
    ],
    chbm10: [
        require('./chbm10/1.jpg'),
        require('./chbm10/2.jpg'),
        require('./chbm10/3.jpg'),
        require('./chbm10/4.jpg'),
        require('./chbm10/5.jpg'),
        require('./chbm10/6.jpg'),
    ],
    chbm11: [
        require('./chbm11/1.jpg'),
        require('./chbm11/2.jpg'),
        require('./chbm11/3.jpg'),
        require('./chbm11/4.jpg'),
        require('./chbm11/5.jpg'),
        require('./chbm11/6.jpg'),
    ],
    chbm12: [
        require('./chbm12/1.jpg'),
        require('./chbm12/2.jpg'),
        require('./chbm12/3.jpg'),
        require('./chbm12/4.jpg'),
        require('./chbm12/5.jpg'),
        require('./chbm12/6.jpg'),
    ],
    chbm13: [
        require('./chbm13/1.jpg'),
        require('./chbm13/2.jpg'),
        require('./chbm13/3.jpg'),
        require('./chbm13/4.jpg')
    ],
    chbm14: [
        require('./chbm14/1.jpg'),
        require('./chbm14/2.jpg'),
        require('./chbm14/3.jpg'),
        require('./chbm14/4.jpg')
    ],
    chbm15: [
        require('./chbm15/1.jpg'),
        require('./chbm15/2.webp'),
        require('./chbm15/3.jpg'),
        require('./chbm15/4.jpg'),
        require('./chbm15/5.jpg'),
        require('./chbm15/6.jpg'),
        require('./chbm15/7.jpg'),
    ],
    chbm16: [
        require('./chbm16/1.jpg'),
        require('./chbm16/2.jpg'),
        require('./chbm16/3.jpg'),
        require('./chbm16/4.jpg'),
        require('./chbm16/5.jpg'),
        require('./chbm16/6.jpg'),
        require('./chbm16/7.jpg'),
        require('./chbm16/8.jpg'),
    ],
    chbm17: [
        require('./chbm17/1.jpg'),
        require('./chbm17/2.jpg'),
        require('./chbm17/3.jpg'),
        require('./chbm17/4.jpg'),
        require('./chbm17/5.jpg'),
        require('./chbm17/6.jpg'),
        require('./chbm17/7.jpg'),
        require('./chbm17/8.jpg'),
    ],
    chbm18: [
        require('./chbm18/1.jpg'),
        require('./chbm18/2.jpg'),
        require('./chbm18/3.jpg'),
        require('./chbm18/4.jpg'),
        require('./chbm18/5.jpg'),
        require('./chbm18/6.jpg'),
        require('./chbm18/7.jpg'),
        require('./chbm18/8.jpg'),
        require('./chbm18/9.jpg'),
    ],
    chbm19: [
        require('./chbm19/1.jpg'),
        require('./chbm19/2.jpg'),
        require('./chbm19/3.jpg'),
        require('./chbm19/4.jpg'),
        require('./chbm19/5.jpg'),
        require('./chbm19/6.jpg'),
        require('./chbm19/7.jpg'),
        require('./chbm19/8.jpg'),
        require('./chbm19/9.jpg'),
    ],
    chbm20: [
        require('./chbm20/1.jpg'),
        require('./chbm20/2.jpg'),
        require('./chbm20/3.jpg'),
        require('./chbm20/4.jpg'),
        require('./chbm20/5.jpg'),
        require('./chbm20/6.jpg'),
        require('./chbm20/7.jpg'),
    ],
    chbm21: [
        require('./chbm21/1.jpg'),
        require('./chbm21/2.jpg'),
        require('./chbm21/3.jpg'),
        require('./chbm21/4.jpg'),
        require('./chbm21/5.jpg'),
        require('./chbm21/6.jpg'),
        require('./chbm21/7.jpg'),
    ],
    chbm22: [
        require('./chbm22/1.jpg'),
        require('./chbm22/2.jpg'),
        require('./chbm22/3.jpg'),
        require('./chbm22/4.jpg'),
        require('./chbm22/5.jpg'),
        require('./chbm22/6.jpg'),
        require('./chbm22/7.jpg'),
        require('./chbm22/8.jpg'),
    ],
    chlines1: [
        require('./chlines1/1.jpg'),
        require('./chlines1/2.jpg'),
        require('./chlines1/3.jpg'),
        require('./chlines1/4.jpg'),
        require('./chlines1/5.jpg'),
    ],
    chlines2: [
        require('./chlines2/1.jpg'),
        require('./chlines2/2.jpg'),
        require('./chlines2/3.jpg'),
        require('./chlines2/4.jpg'),
        require('./chlines2/5.jpg'),
        require('./chlines2/6.jpg'),
    ],
    chlines3: [
        require('./chlines3/1.jpg'),
        require('./chlines3/2.jpg'),
        require('./chlines3/3.jpg'),
        require('./chlines3/4.jpg'),
        require('./chlines3/5.jpg'),
    ],
    chlines4: [
        require('./chlines4/1.jpg'),
        require('./chlines4/2.jpg'),
        require('./chlines4/3.jpg'),
    ],
    chlines5: [
        require('./chlines5/1.jpg'),
        require('./chlines5/2.jpg'),
        require('./chlines5/3.jpg'),
        require('./chlines5/4.jpg'),
        require('./chlines5/5.jpg'),
        require('./chlines5/6.jpg'),
        require('./chlines5/7.jpg'),
        require('./chlines5/8.jpg'),
        require('./chlines5/9.jpg'),
    ],
    chmol2v1: [
        require('./chmol2v1/1.jpg'),
        require('./chmol2v1/2.jpg'),
        require('./chmol2v1/3.jpg'),
    ],
    chmol2v2: [
        require('./chmol2v2/1.jpg'),
    ],
    chmol2v3: [
        require('./chmol2v3/1.jpg'),
    ],
    sbbm1: [
        require('./sbbm1/1.jpg'),
        require('./sbbm1/2.jpg'),
        require('./sbbm1/3.jpg'),
        require('./sbbm1/4.jpg'),
        require('./sbbm1/5.jpg'),
        require('./sbbm1/6.jpg'),
        require('./sbbm1/7.jpg'),
        require('./sbbm1/8.jpg'),
        require('./sbbm1/9.jpg'),
        require('./sbbm1/10.jpg'),
        require('./sbbm1/11.jpg'),
    ],
    sbbm2: [
        require('./sbbm2/1.jpg'),
    ],
    sbbm3: [
        require('./sbbm3/1.jpg'),
    ],
    tabbm1: [
        require('./tabbm1/1.jpg'),
        require('./tabbm1/2.jpg'),
        require('./tabbm1/3.jpg'),
    ],
    tabbm2: [
        require('./tabbm2/1.jpg'),
        require('./tabbm2/2.jpg'),
        require('./tabbm2/3.jpg'),
    ],
    tabbm3: [
        require('./tabbm3/1.jpg'),
        require('./tabbm3/2.jpg'),
    ],
    tabbm4: [
        require('./tabbm4/1.jpg'),
        require('./tabbm4/2.jpg'),
        require('./tabbm4/3.jpg'),
    ],
    tabbm5: [
        require('./tabbm5/1.jpg'),
        require('./tabbm5/2.jpg'),
        require('./tabbm5/3.jpg'),
        require('./tabbm5/4.jpg'),
        require('./tabbm5/5.jpg'),
    ],
    tabbm6: [
        require('./tabbm6/1.jpg'),
        require('./tabbm6/2.jpg'),
        require('./tabbm6/3.jpg'),
        require('./tabbm6/4.jpg'),
        require('./tabbm6/5.jpg'),
        require('./tabbm6/6.jpg'),
    ],
    tabbm7: [
        require('./tabbm7/1.jpg'),
        require('./tabbm7/2.jpg'),
        require('./tabbm7/3.jpg'),
    ],
    tabbm8: [
        require('./tabbm8/1.jpg'),
        require('./tabbm8/2.jpg'),
    ],
    tabbm9: [
        require('./tabbm9/1.jpg'),
        require('./tabbm9/2.jpg'),
        require('./tabbm9/3.jpg'),
        require('./tabbm9/4.jpg'),
    ],
    tabbm10: [
        require('./tabbm10/1.jpg'),
        require('./tabbm10/2.jpg'),
        require('./tabbm10/3.jpg'),
    ],
    tabbm11: [
        require('./tabbm11/1.jpg'),
        require('./tabbm11/2.jpg'),
        require('./tabbm11/3.jpg'),
        require('./tabbm11/4.jpg'),
    ],
    tabbm12: [
        require('./tabbm12/1.jpg'),
        require('./tabbm12/2.jpg'),
        require('./tabbm12/3.jpg'),
    ],
    tabbm13: [
        require('./tabbm13/1.jpg'),
        require('./tabbm13/2.jpg'),
        require('./tabbm13/3.jpg'),
        require('./tabbm13/4.jpg'),
        require('./tabbm13/5.jpg'),
        require('./tabbm13/6.jpg'),
        require('./tabbm13/7.jpg'),
        require('./tabbm13/8.jpg'),
        require('./tabbm13/9.jpg'),
        require('./tabbm13/10.jpg'),
        require('./tabbm13/11.jpg'),
        require('./tabbm13/12.jpg'),
        require('./tabbm13/13.jpg'),
        require('./tabbm13/14.jpg'),
    ],
    tabbm14: [
        require('./tabbm14/1.jpg'),
        require('./tabbm14/2.jpg'),
        require('./tabbm14/3.jpg'),
        require('./tabbm14/4.jpg'),
    ],
    tabbm15: [
        require('./tabbm15/1.jpg'),
        require('./tabbm15/2.jpg'),
        require('./tabbm15/3.jpg'),
        require('./tabbm15/4.jpg'),
        require('./tabbm15/5.jpg'),
        require('./tabbm15/6.jpg'),
        require('./tabbm15/7.jpg'),
        require('./tabbm15/8.jpg'),
        require('./tabbm15/9.jpg'),
    ],
    tabbm16: [
        require('./tabbm16/1.jpg'),
        require('./tabbm16/2.jpg'),
        require('./tabbm16/3.jpg'),
        require('./tabbm16/4.jpg'),
        require('./tabbm16/5.jpg'),
        require('./tabbm16/6.jpg'),
        require('./tabbm16/7.jpg'),
    ],
    tablines1: [
        require('./tablines1/1.jpg'),
        require('./tablines1/2.jpg'),
        require('./tablines1/3.jpg'),
    ],
    tablines2: [
        require('./tablines2/1.jpg'),
        require('./tablines2/2.jpg'),
        require('./tablines2/3.jpg'),
        require('./tablines2/4.jpg'),
        require('./tablines2/5.jpg'),
    ],
    tablines3: [
        require('./tablines3/1.jpg'),
        require('./tablines3/2.jpg'),
        require('./tablines3/3.jpg'),
    ],
    tablines4: [
        require('./tablines4/1.jpg'),
        require('./tablines4/2.jpg'),
        require('./tablines4/3.jpg'),
        require('./tablines4/4.jpg'),
        require('./tablines4/5.jpg'),
    ],
    tablines5: [
        require('./tablines5/1.jpg'),
        require('./tablines5/2.jpg'),
        require('./tablines5/3.jpg'),
        require('./tablines5/4.jpg'),
    ],
    tablines6: [
        require('./tablines6/1.jpg'),
        require('./tablines6/2.jpg'),
        require('./tablines6/3.jpg'),
    ],
    tablines7: [
        require('./tablines7/1.jpg'),
        require('./tablines7/2.jpg'),
    ],
    tablines8: [
        require('./tablines8/1.jpg'),
        require('./tablines8/2.jpg'),
        require('./tablines8/3.jpg'),
        require('./tablines8/4.jpg'),
        require('./tablines8/5.jpg'),
    ],
}

export default CHAIRS;